# Generated by Django 3.2.7 on 2021-09-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('is_complited', models.BooleanField(default=False)),
            ],
        ),
    ]
